# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker-compose build
#      Start app: docker-compose up app
# Start database: docker-compose up db
# Run migrations: docker-compose run migrate
#       Stop all: docker-compose down (add -v to wipe db)
#

volumes:
  postgres_data:

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_HOST: postgres
  DATABASE_NAME: MEOWLS
  DATABASE_USERNAME: meowls_username
  DATABASE_PASSWORD: meowls_1234567890_password
  DATABASE_PORT: 5432

services:
  app:
    image: mayer1a/gbshopserver:latest
    container_name: app
    restart: always
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
  migrate:
    image: mayer1a/gbshopserver:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - postgres
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
  revert:
    image: mayer1a/gbshopserver:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - postgres
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
  postgres:
    restart: unless-stopped
    image: mayer1a/gbshoppostgres:16-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: MEOWLS
      POSTGRES_PASSWORD: meowls_1234567890_password
      POSTGRES_USER: meowls_username
      POSTGRES_HOST: localhost
    ports:
      - '5432:5432'
