name: Deploy to Ubuntu Server, build and run docker

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 1. Checkout repository
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  # 2. Get Docker container ID
  get_container_id:
    runs-on: ubuntu-latest
    needs: checkout
    outputs:
      container_id: ${{ steps.get_container_id.outputs.container_id }}
    steps:
      - name: Get Docker container ID
        id: get_container_id
        run: |
          CONTAINER_ID=$(ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'docker ps -qf name=${{ secrets.CONTAINER_NAME }}')
          echo "::set-output name=container_id::$CONTAINER_ID"

  # 3. Get Docker image ID
  get_image_id:
    runs-on: ubuntu-latest
    needs: get_container_id
    outputs:
      image_id: ${{ steps.get_image_id.outputs.image_id }}
    steps:
      - name: Get Docker image ID
        id: get_image_id
        run: |
          IMAGE_ID=$(ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'docker images -q ${{ secrets.CONTAINER_NAME }}:latest')
          echo "::set-output name=image_id::$IMAGE_ID"

  # 4. Update code
  update_code:
    runs-on: ubuntu-latest
    needs: get_image_id
    steps:
      - name: Update code
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'cd /root/MEOWLSServer/MEOWLSServer/ && git pull origin main'

  # 5. Build Docker image
  build_docker_image:
    runs-on: ubuntu-latest
    needs: update_code
    steps:
      - name: Build Docker image
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'cd /root/MEOWLSServer/MEOWLSServer/ && docker build -t ${{ secrets.CONTAINER_NAME }} .'

  # 6. Stop and remove old container
  stop_remove_old_container:
    runs-on: ubuntu-latest
    needs: build_docker_image
    if: ${{ needs.get_container_id.outputs.container_id != '' }}
    steps:
      - name: Stop and remove old container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'docker container stop ${{ needs.get_container_id.outputs.container_id }} && docker container rm ${{ needs.get_container_id.outputs.container_id }}'

  # 7. Remove old image
  remove_old_image:
    runs-on: ubuntu-latest
    needs: stop_remove_old_container
    if: ${{ needs.get_image_id.outputs.image_id != '' }}
    steps:
      - name: Remove old image
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'docker rmi ${{ needs.get_image_id.outputs.image_id }}'

  # 8. Run new container
  run_new_container:
    runs-on: ubuntu-latest
    needs: remove_old_image
    steps:
      - name: Run new container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} '
            docker run --restart=always \
              --name "${{ secrets.CONTAINER_NAME }}" \
              --network meowls_network \
              -e DATABASE_HOST="${{ secrets.DATABASE_HOST }}" \
              -e DATABASE_NAME="${{ secrets.DATABASE_NAME }}" \
              -e DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
              -e DATABASE_USERNAME="${{ secrets.DATABASE_USERNAME }}" \
              -e DADATA_TOKEN="${{ secrets.DADATA_TOKEN }}" \
              -p "${{ secrets.DATABASE_PORT }}" \
              -d "${{ secrets.CONTAINER_NAME }}:latest"'

  # 9. Clean up unused images and containers
  clean_up:
    runs-on: ubuntu-latest
    needs: run_new_container
    steps:
      - name: Clean up unused images and containers
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'docker system prune -a -f'
