name: Deploy to Ubuntu Server, build and run docker

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 1. Checkout repository
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  # 2. Get Docker container ID
  get_container_id:
    runs-on: ubuntu-latest
    needs: checkout
    outputs:
      container_id: ${{ steps.get_container_id.outputs.container_id }}
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get Docker container ID
        id: get_container_id
        run: |
          CONTAINER_ID=$(ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'docker ps -qf name=${{ secrets.CONTAINER_NAME }}')
          echo "container_id=$CONTAINER_ID" >> "$GITHUB_OUTPUT"

  # 3. Get Docker image ID
  get_image_id:
    runs-on: ubuntu-latest
    needs: get_container_id
    outputs:
      image_id: ${{ steps.get_image_id.outputs.image_id }}
      container_id: ${{ needs.get_container_id.outputs.container_id }}
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get Docker image ID
        id: get_image_id
        run: |
          IMAGE_ID=$(ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'docker images -q ${{ secrets.CONTAINER_NAME }}')
          echo "image_id=$IMAGE_ID" >> "$GITHUB_OUTPUT"
          echo "container_id=${{ needs.get_container_id.outputs.container_id }}" >> "$GITHUB_OUTPUT"

  # 4. Update code
  update_code:
    runs-on: ubuntu-latest
    needs: get_image_id
    outputs:
      image_id: ${{ needs.get_image_id.outputs.image_id }}
      container_id: ${{ needs.get_image_id.outputs.container_id }}
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Extract branch name
        id: extract_branch
        run: |
          echo "CONTAINER_ID: ${{ needs.get_image_id.outputs.container_id }}"
          echo "IMAGE_ID: ${{ needs.get_image_id.outputs.image_id }}"

          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "image_id=${{ needs.get_image_id.outputs.image_id }}" >> "$GITHUB_OUTPUT"
          echo "container_id=${{ needs.get_image_id.outputs.container_id }}" >> "$GITHUB_OUTPUT"

      - name: Update code
        run: |
          BRANCH_NAME="${{ steps.extract_branch.outputs.branch }}"
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'cd /root/MEOWLSServer/MEOWLSServer/ && git pull origin $BRANCH_NAME'

  # 5. Build Docker image
  build_docker_image:
    runs-on: ubuntu-latest
    needs: update_code
    outputs:
      image_id: ${{ needs.update_code.outputs.image_id }}
      container_id: ${{ needs.update_code.outputs.container_id }}
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build Docker image
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'cd /root/MEOWLSServer/MEOWLSServer/ && docker build -t ${{ secrets.CONTAINER_NAME }} .'
          echo "image_id=${{ needs.update_code.outputs.image_id }}" >> "$GITHUB_OUTPUT"
          echo "container_id=${{ needs.update_code.outputs.container_id }}" >> "$GITHUB_OUTPUT"

  # 6. Stop and remove old container
  stop_remove_old_container:
    runs-on: ubuntu-latest
    needs: build_docker_image
    outputs:
      image_id: ${{ needs.build_docker_image.outputs.image_id }}
    if: ${{ needs.build_docker_image.outputs.container_id != '' }}
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Stop and remove old container
        run: |
          echo "CONTAINER_ID ${{ needs.build_docker_image.outputs.container_id }}"
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'docker container stop ${{ needs.build_docker_image.outputs.container_id }} && docker container rm ${{ needs.build_docker_image.outputs.container_id }}'
          echo "image_id=${{ needs.build_docker_image.outputs.image_id }}" >> "$GITHUB_OUTPUT"

  # 7. Remove old image
  remove_old_image:
    runs-on: ubuntu-latest
    needs:
      - stop_remove_old_container
      - build_docker_image
    if: ${{ always() && (needs.stop_remove_old_container.outputs.image_id != '' || needs.build_docker_image.outputs.image_id != '') }}
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Remove old image
        run: |
          echo "IMAGE_ID ${{ needs.stop_remove_old_container.outputs.image_id || needs.build_docker_image.outputs.image_id }}"
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'docker rmi ${{ needs.stop_remove_old_container.outputs.image_id || needs.build_docker_image.outputs.image_id }}'

  # 8. Run new container
  run_new_container:
    runs-on: ubuntu-latest
    needs:
      - remove_old_image
      - build_docker_image
    if: ${{ always() }}
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run new container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} '
            docker run --restart=always \
              --name "${{ secrets.CONTAINER_NAME }}" \
              --network meowls_network \
              -e DATABASE_HOST="${{ secrets.DATABASE_HOST }}" \
              -e DATABASE_NAME="${{ secrets.DATABASE_NAME }}" \
              -e DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
              -e DATABASE_USERNAME="${{ secrets.DATABASE_USERNAME }}" \
              -e DADATA_TOKEN="${{ secrets.DADATA_TOKEN }}" \
              -p "${{ secrets.DATABASE_PORT }}" \
              -d "${{ secrets.CONTAINER_NAME }}:latest"'

  # 9. Clean up unused images and containers
  clean_up:
    runs-on: ubuntu-latest
    needs: run_new_container
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clean up unused images and containers
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'docker system prune -a -f'
